apiVersion: apps/v1
kind: Deployment
metadata:
  name: devforum-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devforum
  template:
    metadata:
      labels:
        app: devforum
    spec:
      containers:
      - name: devforum
        image: devforum-app:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:admin123@postgres-service:5432/devforum"

        - name: NEXTAUTH_SECRET
          value: "mysecret123"

        - name: NEXTAUTH_URL
          value: "http://localhost:3000"

        - name: GOOGLE_CLIENT_ID
          value: "338895037657-63p2cto2t0j4ldb6tgunbothih79mb1t.apps.googleusercontent.com"

        - name: GOOGLE_CLIENT_SECRET
          value: "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"